version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: foodc
      DB_USER: root
      DB_PASS: root
    networks:
      - app_net
  
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./foodc.sql:/docker-entrypoint-initdb.d/foodc.sql
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
